Readme güncellemeleri ve unit için enum'dan string literal'e geçiş
sarpere/heatmapjs-react pull request #8
Opened 2022-12-06 08:46 UTC by ubaranzorlu

Selamlar, birkaç güncelleme yaptım repo'da. Sadece package.json daki değişiklikten emin değilim. Senin halin bende build olmuyordu, ben de official repo'ya bağladım şu an bende sorunsuz çalışıyor.

## Readme
Readme'de Prop'lar yanlış gösterilmişti, ben kullanırken kafam karıştığı için girip doğru şeklini bulup güncelledim.

## Unit Type Enum'dan String Literal'e Geçirilmesi
Enum'u kendi projelerimde referanslayamadım o yüzden bunu string literal olarak tutmak daha temiz ve kolay olur diye düşündüm.

2022-12-06 09:20 UTC, sarpere commented
Burada consistency sağlamak için enum kullanmak daha doğru olur. Sanırım dediğin gibi referanslama konusunda bir sorun olmuş. Enum'u kaldırmaktansa type definition tarafındaki hatayı çözmek daha sağlıklı olur.

2022-12-06 15:37 UTC, sarpere requested changes
Unit enum ile alakalı yaptığın değişiklikleri kaldırabilirsin. Ben unit typing ile alakalı sorun başka bir PR açarak çözdüm. Enum'u bozmaktansa basit bir yol ile enum üzerinden type gösterimi ekledim. [#9]

2022-12-07 07:33 UTC, ubaranzorlu commented
Only kept the changes for Readme.

2022-12-07 07:46 UTC, sarpere approved these changes

2022-12-07 07:46 UTC, merged